# Generated by Django 5.2 on 2025-07-23 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Harakat')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Harakat jurnali',
                'verbose_name_plural': 'Harakat jurnallari',
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
