# Generated by Django 5.2 on 2025-04-25 21:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Xaridor nomi')),
                ('phone_number', models.CharField(help_text='+998901234567', max_length=12, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998 bilan boshlanishi va 9 ta raqamdan iborat bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami')),
                ('initial_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qarzdorlik")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': 'Xaridor',
                'verbose_name_plural': 'Xaridorlar',
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=20, verbose_name="To'lov turi")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.customer', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': "Xaridor to'lovi",
                'verbose_name_plural': "Xaridor to'lovlari",
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ta'minotchi nomi")),
                ('phone_number', models.CharField(help_text='+998901234567', max_length=12, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998 bilan boshlanishi va 9 ta raqamdan iborat bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami')),
                ('initial_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qarzdorlik")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': "Ta'minotchi",
                'verbose_name_plural': "Ta'minotchilar",
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=20, verbose_name="To'lov turi")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': "Ta'minotchi to'lovi",
                'verbose_name_plural': "Ta'minotchi to'lovlari",
            },
        ),
    ]
