# Generated by Django 5.2 on 2025-07-21 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Xaridor nomi')),
                ('phone_number', models.CharField(help_text='+998901234567', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami + bilan boshlanishi va undan keyin 12 ta raqamdan iborat bo'lishi kerak (umumiy 13 ta belgi).", regex='^\\+\\d{12}$')], verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kompaniya nomi')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='INN')),
                ('initial_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qarzdorlik")),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kredit limiti')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma foizi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': 'Xaridor',
                'verbose_name_plural': 'Xaridorlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('check', 'Chek')], max_length=20, verbose_name="To'lov turi")),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hujjat raqami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.customer', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': "Xaridor to'lovi",
                'verbose_name_plural': "Xaridor to'lovlari",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ta'minotchi nomi")),
                ('phone_number', models.CharField(help_text='+998901234567', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami + bilan boshlanishi va undan keyin 12 ta raqamdan iborat bo'lishi kerak (umumiy 13 ta belgi).", regex='^\\+\\d{12}$')], verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kompaniya nomi')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='INN')),
                ('initial_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qarzdorlik")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': "Ta'minotchi",
                'verbose_name_plural': "Ta'minotchilar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('check', 'Chek')], max_length=20, verbose_name="To'lov turi")),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hujjat raqami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': "Ta'minotchi to'lovi",
                'verbose_name_plural': "Ta'minotchi to'lovlari",
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
