# Generated by Django 5.2 on 2025-04-28 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='+998901234567', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami + bilan boshlanishi va undan keyin 12 ta raqamdan iborat bo'lishi kerak (umumiy 13 ta belgi).", regex='^\\+\\d{12}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(help_text='+998901234567', max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami + bilan boshlanishi va undan keyin 12 ta raqamdan iborat bo'lishi kerak (umumiy 13 ta belgi).", regex='^\\+\\d{12}$')], verbose_name='Telefon raqami'),
        ),
    ]
