# Generated by Django 5.2 on 2025-07-21 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Faktura raqami')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan summa")),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Qarz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Faktura raqami')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan summa")),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Qarz')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Foyda')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Rasm')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miqdor')),
                ('minimum_quantity', models.PositiveIntegerField(default=10, verbose_name='Minimal miqdor')),
                ('unit', models.CharField(default='dona', max_length=20, verbose_name="O'lchov birligi")),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shtrix kod')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OutgoingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sotuv narxi')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tan narxi')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Foyda')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Partiya raqami')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outgoing', verbose_name='Chiqim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Chiqim elementi',
                'verbose_name_plural': 'Chiqim elementlari',
            },
        ),
        migrations.CreateModel(
            name='IncomingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narx')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Partiya raqami')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.incoming', verbose_name='Kirim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Kirim elementi',
                'verbose_name_plural': 'Kirim elementlari',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ombor nomi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.warehouse', verbose_name='Ombor'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoings', to='inventory.warehouse', verbose_name='Ombor'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomings', to='inventory.warehouse', verbose_name='Ombor'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'warehouse')},
        ),
    ]
