# Generated by Django 5.2 on 2025-04-25 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami xarid summasi')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan pul")),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Qolgan qarz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami xarid summasi')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan pul")),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Qolgan qarz')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Foyda')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miqdor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OutgoingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narx')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami summa')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Foyda')),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outgoing')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Chiqim elementi',
                'verbose_name_plural': 'Chiqim elementlari',
            },
        ),
        migrations.CreateModel(
            name='IncomingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narx')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami summa')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.incoming')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Kirim elementi',
                'verbose_name_plural': 'Kirim elementlari',
            },
        ),
    ]
