# Generated by Django 5.2 on 2025-07-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, help_text="Mahsulot qo'shilganda avtomatik qo'shiladi", verbose_name="Boshlang'ich miqdor"),
        ),
    ]
