# Generated by Django 5.2 on 2025-07-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Mahsulot'),
        ),
    ]
